
#pragma DONT_COMPILE_THIS_FILE


// This file contains defines for some of the messages
#define MSG_INTRO  "\nWelcome to ĞÒÏÚÁÃ CustomÔÆ\na Quake ÔÆ MOD by ShakaUVM\nwww®telefragged®com¯shaka\n\nŸ\n\n"
#define MSG_INTRO2 "Based on the aussie ver by SB-1\nModified version by Clan Prozac\n\nŸ\n\nGet any files needed at:\n\nhttp:¯¯quake®prozac®net¯"
                                              //, aka óC”’’’
//#define MSG_CUTFVERSION "CustomÔÆ version ö3®2®OfN"
#define MSG_CUTFVERSION   "ĞÒÏÚÁÃ CustomÔÆ ö3®2®OfN4"

// Comments CenterPrinted when a player gets the CTF flag
#define MSG_CTF_FLAG_GRAB_TEAM1   "You got the enemy flag!\n\nFlee!"
#define MSG_CTF_FLAG_GRAB_TEAM2   "You got the enemy flag!\n\nHead for home!"
#define MSG_CTF_FLAG_GRAB_TEAM3   "You got the enemy flag!\n\nReturn to base!"
#define MSG_CTF_FLAG_GRAB_TEAM4   "You got the enemy flag!\n\n<Insert witty comment here>"
#define MSG_CTF_FLAG_GRAB_TEAM5_1 "You got the enemy flag!\n\nRed's dead baby, Red's dead..."
#define MSG_CTF_FLAG_GRAB_TEAM5_2 "You got the enemy flag!\n\n"
#define MSG_CTF_FLAG_GRAB_TEAM6   "You got the enemy flag!\n\n"
#define MSG_CTF_FLAG_GRAB_TEAM7   "Is that a flag in your pocket\nor a you just happy to see me?"
